INSERT INTO ROLE VALUES (1, 'ADMIN');
INSERT INTO ROLE VALUES (2, 'USER');

INSERT INTO USER VALUES (1,	1, 'a@b.c', 'b', 'a', '$2a$10$SJYQC39mcqqM9GBV5evRT.FAAU./GNGRmzKXVbyUxFZ7IBtvrF7bC');
INSERT INTO USER_ROLE VALUES (1, 1);

